const DB_USERS_COLLECTION_NAME = "users";
const DB_PRODES_COLLECTION_NAME = "prodes";
const DB_USERS_PRODES_COLLECTION_NAME = "prodes";

export {
	DB_USERS_COLLECTION_NAME,
	DB_PRODES_COLLECTION_NAME,
	DB_USERS_PRODES_COLLECTION_NAME,
};
